<?php
/**
 * Implementation of hook_menu().
 */

function uc_shipping_zones_menu(){
  $items = array();
  
  $items['admin/store/settings/quotes/methods/zones'] = array(
    'title' => 'Shipping zones',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('uc_shipping_zones_admin', 6),
    'access arguments' => array('configure quotes'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'uc_shipping_zones_admin.inc'
  );

  return $items;
}

/**
 * Implementation of hook_theme().
 */
function uc_shipping_zones_theme($form){
  return array(
    'uc_shipping_zones_admin' => array(
      'arguments' => array('form' => NULL, 'zid' => NULL),
      'file' => 'uc_shipping_zones_admin.inc',
    ),
  );
}

/**
 * Get shipping zones
 * 
 * @param $country
 * country name or code (optional)
 * 
 * @return
 * an array containing the shipping zones. 
 */
function uc_shipping_zones_get($country = NULL) {

    if (! $country) $r = db_query("SELECT * FROM {uc_shipping_zones} ORDER BY name");
    else {
        if (is_int($country)) {
            $c->name = uc_country_get_by_id($country);
            $c->id = $country;
        }
        else {
            $c->name = $country;
            $c->id = db_result(db_query("SELECT country_name FROM {uc_countries} WHERE country_name = %s", $country));
        }
        $r = db_query("SELECT * FROM {uc_shipping_zones} WHERE countries LIKE '%%%s%%' ORDER BY name", $c->name . ',' . $c->id);
        return db_fetch_object($r);
    }

    $rows = array();
    while ($row = db_fetch_object($r)) $rows[] = $row;
    
    return $rows;
}
/**
 * Returns shipping zones ready to feed a selectbox
 */
function uc_shipping_zones_get_select() {
    $rows = array();
    $r = db_query("SELECT zid,name FROM {uc_shipping_zones} ORDER BY name");
    while ($row = db_fetch_object($r)) $rows[$row->zid] = $row->name;
    return $rows;
}